name       : meld
version    : 3.20.1
release    : 18
source     :
    - https://download.gnome.org/sources/meld/3.20/meld-3.20.1.tar.xz : a54843bc4d6cb1d31d0a58aa725091622194d50c32ef67026b35c86dda3cb249
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Meld is a visual diff and merge tool targeted at developers.
description: |
    Meld is a visual diff and merge tool targeted at developers.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
rundeps    :
    - libgtksourceview3
    - python3-cairo
    - python3-dbus
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install

    # I prefer using the actionable macro and removing this
    rm -v $installdir/usr/share/icons/hicolor/icon-theme.cache
    rm -v $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
