name       : meld
version    : 3.21.0
release    : 24
source     :
    - https://download.gnome.org/sources/meld/3.21/meld-3.21.0.tar.xz : b680114d5ab793324549fd58f4eb202d8e280c0633a0b765ede6dfb34160a81b
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Meld is a visual diff and merge tool targeted at developers.
description: |
    Meld is a visual diff and merge tool targeted at developers.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
rundeps    :
    - libgtksourceview
    - python3-cairo
    - python3-dbus
    - python3-gobject
setup      : |
    # They don't actually replace this so it just ends up broken
    sed -i 's:@icon@:meld:g' data/org.gnome.meld.desktop.in.in
build      : |
    %python3_setup
install    : |
    %python3_install

    # I prefer using the actionable macro and removing this
    rm -v $installdir/usr/share/icons/hicolor/icon-theme.cache
    rm -v $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm -rf $installdir/usr/share/doc
