name       : meld
version    : 3.18.3
release    : 15
source     :
    - https://download.gnome.org/sources/meld/3.18/meld-3.18.3.tar.xz : 960ea71e82cedcb8ec89ae71704fdf21c70fa95bc41dc8511f2120074cc7c16e
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Meld is a visual diff and merge tool targeted at developers.
description: |
    Meld is a visual diff and merge tool targeted at developers.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
rundeps    :
    - libgtksourceview
    - python3-cairo
    - python3-dbus
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install

    # I prefer using the actionable macro and removing this
    rm -v $installdir/usr/share/icons/hicolor/icon-theme.cache
    rm -v $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
