name       : meld
version    : 3.16.4
release    : 6
source     :
    - https://download.gnome.org/sources/meld/3.16/meld-3.16.4.tar.xz : 93c4f928319dae7484135ab292fe6ea4254123e8219549a66d3e2deba6a38e67
license    : GPL-2.0
component  : office
summary    : Meld is a visual diff and merge tool targeted at developers.
description: |
    Meld is a visual diff and merge tool targeted at developers.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(python-2.7)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-3.0)
    - itstool
    - intltool
rundeps    :
    - libgtksourceview
    - python-cairo
    - python-gobject
    - python-dbus
install    : |
    unset srcdir
    python2 setup.py install --root=%installroot% --no-compile -O0
    rm $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm $installdir/usr/share/icons/hicolor/icon-theme.cache
