name       : meld
version    : 3.21.0
release    : 29
source     :
    - https://download.gnome.org/sources/meld/3.21/meld-3.21.0.tar.xz : b680114d5ab793324549fd58f4eb202d8e280c0633a0b765ede6dfb34160a81b
homepage   : https://meldmerge.org/
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Meld is a visual diff and merge tool targeted at developers.
description: |
    Meld is a visual diff and merge tool targeted at developers.
builddeps  :
    - pkgconfig(gtksourceview-4)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - itstool
rundeps    :
    - libgtksourceview4
    - python3-dbus
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
