name       : meld
version    : 3.16.2
release    : 4
source     :
    - https://download.gnome.org/sources/meld/3.16/meld-3.16.2.tar.xz : 2dd3f58b95444bf721e0c912668c29cf8f47a402440b772ea12c4b9a0c94966f
license    : GPL-2.0
component  : office
summary    : Meld is a visual diff and merge tool targeted at developers.
description: |
    Meld is a visual diff and merge tool targeted at developers.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(python-2.7)
    - pkgconfig(pycairo)
    - pkgconfig(pygobject-3.0)
    - itstool
    - intltool
rundeps    :
    - libgtksourceview
    - python-cairo
    - python-gobject
    - python-dbus
install    : |
    unset srcdir
    python2 setup.py install --root=%installroot% --no-compile -O0
    rm $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm $installdir/usr/share/icons/hicolor/icon-theme.cache
